# Secrets Manager entries for ngencerf services.
# Each secret is generated by random_password and stored under the env-wide
# KMS CMK (aws_kms_key.main). ECS task definitions reference these ARNs to
# inject the values as env vars at task start.
# NIST SC-12, IA-5: high-entropy generated secrets, customer-managed at-rest key.

# --- Env-wide KMS CMK -------------------------------------------------
# SC-28: customer-managed key for at-rest encryption across Secrets Manager,
# RDS, EFS, Redis, ECS log groups. One CMK per env (vs per-domain) for
# simpler key policy and a single audit surface.
# SC-12: enable_key_rotation = true rotates the underlying material annually.

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# Key policy required because CloudWatch Logs needs an explicit grant from the
# key resource policy to encrypt log streams (unlike RDS/EFS/Secrets/Redis,
# which work via IAM identity policies on the caller). Root statement preserves
# the default IAM-mediated access so the other consumers keep working.
# AC-6: EncryptionContext condition scopes the logs grant to /aws/ecs/<prefix>/*.
data "aws_iam_policy_document" "kms_main" {
  statement {
    sid     = "EnableIAMUserPermissions"
    effect  = "Allow"
    actions = ["kms:*"]
    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }
    resources = ["*"]
  }

  statement {
    sid    = "AllowCloudWatchLogsEncryption"
    effect = "Allow"
    actions = [
      "kms:Encrypt*",
      "kms:Decrypt*",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:Describe*",
    ]
    principals {
      type        = "Service"
      identifiers = ["logs.${data.aws_region.current.name}.amazonaws.com"]
    }
    resources = ["*"]
    condition {
      test     = "ArnLike"
      variable = "kms:EncryptionContext:aws:logs:arn"
      values = [
        "arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:/aws/ecs/${var.name_prefix}/*",
        "arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:aws-waf-logs-${var.name_prefix}",
      ]
    }
  }
}

resource "aws_kms_key" "main" {
  description             = "${var.name_prefix} CMK (Secrets Manager, RDS, EFS, Redis, ECS Logs)"
  deletion_window_in_days = var.production ? 30 : 7
  enable_key_rotation     = true
  policy                  = data.aws_iam_policy_document.kms_main.json
}

resource "aws_kms_alias" "main" {
  name          = "alias/${var.name_prefix}-main"
  target_key_id = aws_kms_key.main.key_id
}

# Preserve the underlying KMS key across the per-domain -> per-env collapse.
# The alias is replaced (KMS aliases are immutable on rename); the key
# material stays put, so it avoids a 7-day pending-deletion window.
moved {
  from = aws_kms_key.secrets
  to   = aws_kms_key.main
}

# --- DB password ------------------------------------------------------

resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%^&*()-_+[]{}<>?." # RDS forbids / " @
}

resource "aws_secretsmanager_secret" "db" {
  name                    = "${var.name_prefix}/db/password"
  kms_key_id              = aws_kms_key.main.arn
  recovery_window_in_days = var.production ? 30 : 0
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id     = aws_secretsmanager_secret.db.id
  secret_string = random_password.db.result
}

# --- Django SECRET_KEY ------------------------------------------------

resource "random_password" "django_secret_key" {
  length  = 50
  special = false
}

resource "aws_secretsmanager_secret" "django_secret_key" {
  name                    = "${var.name_prefix}/django/secret-key"
  kms_key_id              = aws_kms_key.main.arn
  recovery_window_in_days = var.production ? 30 : 0
}

resource "aws_secretsmanager_secret_version" "django_secret_key" {
  secret_id     = aws_secretsmanager_secret.django_secret_key.id
  secret_string = random_password.django_secret_key.result
}

# --- LDAP bind (Active Directory service account) ---------------------
# Read-only AD service account used for LDAP-bind auth. This secret is
# created and owned OUTSIDE this stack (by the AD / account admins), so we
# look it up by NAME for its ARN only and never read its version, so the
# bind password never enters Terraform state. ECS pulls the value straight
# from Secrets Manager at task start (django.tf secrets block). IA-5.
data "aws_secretsmanager_secret" "ldap_bind" {
  count = var.enable_active_directory ? 1 : 0
  name  = var.ldap_bind_secret_name
}
